export const states = [
  {id: 1, name: 'Andhra Pradesh'},
  {id: 2, name: 'Arunachal Pradesh'},
  {id: 3, name: 'Assam'},
  {id: 4, name: 'Bihar'},
  {id: 5, name: 'Chhattisgarh'},
  {id: 6, name: 'Goa'},
  {id: 7, name: 'Gujarat'},
  {id: 8, name: 'Haryana'},
  {id: 9, name: 'Himachal Pradesh'},
  {id: 10, name: 'Jharkhand'},
  {id: 11, name: 'Karnataka'},
  {id: 12, name: 'Kerala'},
  {id: 13, name: 'Madhya Pradesh'},
  {id: 14, name: 'Maharashtra'},
  {id: 15, name: 'Manipur'},
  {id: 16, name: 'Meghalaya'},
  {id: 17, name: 'Mizoram'},
  {id: 18, name: 'Nagaland'},
  {id: 19, name: 'Odisha'},
  {id: 20, name: 'Punjab'},
  {id: 21, name: 'Rajasthan'},
  {id: 22, name: 'Sikkim'},
  {id: 23, name: 'Tamil Nadu'},
  {id: 24, name: 'Telangana'},
  {id: 25, name: 'Tripura'},
  {id: 26, name: 'Uttar Pradesh'},
  {id: 27, name: 'Uttarakhand'},
  {id: 28, name: 'West Bengal'},
];

export const cities = [
  {id: 1, name: 'Hyderabad'},
  {id: 2, name: 'Visakhapatnam'},
  {id: 3, name: 'Vijayawada'},
  {id: 4, name: 'Guntur'},
  {id: 5, name: 'Nellore'},
  {id: 6, name: 'Kurnool'},
  {id: 7, name: 'Rajahmundry'},
  {id: 8, name: 'Tirupati'},
  {id: 9, name: 'Kakinada'},
  {id: 10, name: 'Anantapur'},
  {id: 11, name: 'Itanagar'},
  {id: 12, name: 'Naharlagun'},
  {id: 13, name: 'Tawang'},
  {id: 14, name: 'Bomdila'},
  {id: 15, name: 'Pasighat'},
  {id: 16, name: 'Ziro'},
  {id: 17, name: 'Roing'},
  {id: 18, name: 'Tezu'},
  {id: 19, name: 'Anini'},
  {id: 20, name: 'Along'},
];
